#!/bin/bash

# ---------------------------------------------- #
# Helper script for kernel maintenance in BirbOS #
# ---------------------------------------------- #

set -e

println()
{
    case $1 in
        ERROR) echo -e "\e[31mERROR: $2\e[0m" ;;
        WARNING) echo -e "\e[35mWARNING: $2\e[0m" ;;
        *) echo -e "\e[32m=> \e[0m$@" ;;
    esac
}


print_help()
{
	echo "Usage: kernel [OPTION]"
	echo ""
	echo "  -r  --reinstall           reinstall the kernel"
	echo "  -u  --upgrade             upgrade the kernel"
	echo "  -l  --list                list kernels"
	echo "  -s  --set [version]       change the current kernel to the given version"
}

nvidia_notification()
{
	# Check for nvidia drivers
	if [ -n "$(grep "nvidia-drivers" /var/lib/birb/nest )" ]
	then
		println WARNING "To finish the installation, you need to reinstall nvidia drivers"
		echo "You can reinstall the nvidia drivers after a reboot (in the TTY)"
		echo -e "with birb by running this command: \e[1mbirb nvidia-drivers\e[0m"
	fi
}

reinstall()
{
	println "Compiling the kernel"
	cd /usr/src/linux
	sudo make -j$(nproc)

	println "Installing kernel modules"
	sudo make modules_install

	println "Mounting the boot partition"
	[ -z "$(df | grep "/boot")" ] && sudo mount $BOOT_PARTITION /boot

	println "Installing the BirbOS kernel files to /boot"
	KERNEL_VERSION="$(file /usr/src/linux | awk '{print $5}' | xargs basename | cut -d'-' -f2)"

	sudo cp -iv /usr/src/linux/arch/x86/boot/bzImage /boot/vmlinuz-${KERNEL_VERSION}-birbos
	sudo cp -iv /usr/src/linux/System.map /boot/System.map-${KERNEL_VERSION}

	nvidia_notification
}

get_current_kernel_version()
{
	file /usr/src/linux | awk '{print $5}' | grep -o "[0-9]*\.[0-9]*\.[0-9]*"
}

verify_shasum()
{
	println "Fetching sha256sums.asc from kernel.org"
	REMOTE_SHASUM="$(curl -s https://cdn.kernel.org/pub/linux/kernel/v${MAJOR_VERSION}.x/sha256sums.asc | grep "linux-${VERSION}.tar.xz" | cut -d' ' -f1)"
	echo $REMOTE_SHASUM

	println "Verifying the shasum"
	LOCAL_SHASUM="$(sha256sum $TARBALL_PATH | cut -d' ' -f1)"
	echo $LOCAL_SHASUM

	if [ "$LOCAL_SHASUM" != "$REMOTE_SHASUM" ]
	then
		println ERROR "The shasums didn't match! Removing the downloaded tarball..."
		sudo rm -v $TARBALL_PATH
		echo "Update cancelled"
		exit 1
	fi

	echo "Shasum verification was successful!"
}

verify_signature()
{
	println "Adding developer GPG-keys"

	# Linus Torvalds
	gpg --tofu-policy good "ABAF 11C6 5A29 70B1 30AB  E3C4 79BE 3E43 0041 1886"

	# Greg Kroah-Hartman
	gpg --tofu-policy good "647F 2865 4894 E3BD 4571  99BE 38DB BDC8 6092 693E"

	# Sasha Levin
	gpg --tofu-policy good "E27E 5D8A 3403 A2EF 6687  3BBC DEA6 6FF7 9777 2CDC"

	for i in {torvalds,gregkh,sashal}@kernel.org
	do
		gpg --locate-keys $i
	done

	println "Verifying the signature"
	TEMPDIR="$(mktemp -d /tmp/linux-signatureXXXXX)"
	SIGNATURE_PATH="$TEMPDIR/linux-${VERSION}.tar.sign"
	curl -s https://cdn.kernel.org/pub/linux/kernel/v${MAJOR_VERSION}.x/linux-${VERSION}.tar.sign > $SIGNATURE_PATH

	COUNT="$(sudo xz -cd $TARBALL_PATH \
		| gpg --verify --trust-model tofu --status-fd=1 $SIGNATURE_PATH - \
		| grep -c -E '^\[GNUPG:\] (GOODSIG|VALIDSIG)')"

	# Remove the signature file
	rm -r $TEMPDIR

	if [[ ${COUNT} -lt 2 ]]
	then
		println ERROR "Kernel source tarball signature could not be verified!"
		exit 1
	fi

	echo "Signature verification was successful!"
}

install_new_kernel()
{
	SOURCE_BASENAME="$(basename $TARBALL_SOURCE)"

	println "Downloading $SOURCE_BASENAME"
	cd /var/cache/distfiles
	[ ! -f $(basename $TARBALL_SOURCE) ] && sudo wget -q --show-progress $TARBALL_SOURCE

	TARBALL_PATH="/var/cache/distfiles/$SOURCE_BASENAME"

	verify_shasum
	verify_signature

	println "Extracting kernel sources to /usr/src"
	cd /usr/src
	sudo tar -xf $TARBALL_PATH

	println "Updating the /usr/src/linux symlink"
	sudo rm -fv /usr/src/linux
	sudo ln -sv /usr/src/linux-$VERSION /usr/src/linux

	println "Cleaning kernel source tree"
	cd /usr/src/linux
	sudo make mrproper

	println "Copying kernel configurations"
	sudo cp -v /usr/src/linux-$CURRENT_KERNEL_VERSION/.config /usr/src/linux-$VERSION/

	println "Updating the kernel configuration file"
	sudo make oldconfig

	reinstall
}

upgrade()
{
	println "Checking kernel.org for new kernel releases..."

	# Scrape the latest stable kernel release from kernel.org
	LATEST_STABLE_HTML="$(curl -s https://kernel.org/ | grep -m 1 -A 3 "stable:")"

	VERSION="$(echo "$LATEST_STABLE_HTML" | sed '2!d' | grep -o "[0-9]*\.[0-9]*\.[0-9]*")"
	MAJOR_VERSION="$(echo $VERSION | cut -d'.' -f1)"
	RELEASE_DATE="$(echo "$LATEST_STABLE_HTML" | sed '3!d' | grep -o "[0-9]*-[0-9]*-[0-9]")"
	TARBALL_SOURCE="$(echo "$LATEST_STABLE_HTML" | tail -n1 | grep -o "https://cdn.kernel.org/pub/linux/kernel/v[0-9].x/linux-[0-9]*\.[0-9]*\.[0-9]*\.tar.xz")"

	CURRENT_KERNEL_VERSION="$(get_current_kernel_version)"

	# Check if the latest possible kernel is already installed
	if [ "$VERSION" == "$CURRENT_KERNEL_VERSION" ]
	then
		echo "Kernel is already up-to-date!"
		exit 0
	fi

	echo "New stable kernel release is available!"
	echo -e "Version: \t$VERSION"
	echo -e "Release date: \t$RELEASE_DATE"
	echo ""
	echo "Currently installed kernel version: $CURRENT_KERNEL_VERSION"
	echo ""
	read -p "Would you like to upgrade? [y/N]: " AGREE_KERNEL_UPGRADE

	case $AGREE_KERNEL_UPGRADE in
		y|Y)
			install_new_kernel
			;;

		*)
			echo "Upgrade cancelled"
			exit 0
			;;
	esac
}

list_kernels()
{
	KERNELS="$(ls /usr/src | grep -w "linux-[0-9]*\.[0-9]*\.[0-9]*")"
	CURRENT_KERNEL="$(file /usr/src/linux | grep -ow "linux-[0-9]*\.[0-9]*\.[0-9]*")"

	CHECKBOX_CHECKED="\[x\]"
	CHECKBOX_NOT_CHECKED="\[ \]"

	# Format the list as a checkbox list
	KERNELS="$(echo "$KERNELS" | sed "s/^/${CHECKBOX_NOT_CHECKED} /")"

	# Mark the currently installed kernel as checked
	KERNELS="$(echo "$KERNELS" | sed "s/^${CHECKBOX_NOT_CHECKED} ${CURRENT_KERNEL}/${CHECKBOX_CHECKED} ${CURRENT_KERNEL}/")"

	# Print out the kernel list
	echo "$KERNELS" | sed 's/linux-//'
}

# Args: [kernel version]
set_kernel()
{
	# Check if the given kernel version is installed
	if [ ! -d /usr/src/linux-${1} ]
	then
		println ERROR "Kernel version $1 not available in /usr/src"
		exit 1
	fi

	# Verify that the kernel we are changing to has a config file
	if [ ! -f /usr/src/linux-${1}/.config ]
	then
		println ERROR "Kernel version $1 doesn't have a .config file"
		exit 1
	fi

	# Switch the symlink over
	sudo rm -v /usr/src/linux
	sudo ln -sv /usr/src/linux-${1} /usr/src/linux

	echo "Kernel switched to linux-${1}"
}

# Handle arguments
case $1 in
	-r|--reinstall) reinstall ;;
	-u|--upgrade) upgrade ;;
	-l|--list) list_kernels ;;
	-s|--set) set_kernel $2 ;;

	*)
		print_help
		exit 1
		;;
esac
